/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-дек-2024 17:44:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 

/* Drop Tables */

--DROP TABLE IF EXISTS item CASCADE;

/* Create Tables */

CREATE TABLE item
(
	id bigserial NOT NULL,
	order_id bigserial NOT NULL,
	service_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE item ADD CONSTRAINT "PK_item"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_item_order" ON item (order_id ASC)
;

CREATE INDEX "IXFK_item_service" ON item (service_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE item ADD CONSTRAINT "FK_item_order"
	FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE item ADD CONSTRAINT "FK_item_service"
	FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 
