/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-дек-2024 15:43:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

--DROP TABLE IF EXISTS item_credit_card CASCADE;

/* Create Tables */

CREATE TABLE item_credit_card
(
	id bigserial NOT NULL,
	item_id bigint NOT NULL,
	credit_limit numeric(19,2) NOT NULL,
	interest_rate numeric(5,2) NOT NULL,
	loan_term integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE item_credit_card ADD CONSTRAINT "PK_item_credit_card"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_item_credit_card_item" ON item_credit_card (item_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE item_credit_card ADD CONSTRAINT "FK_item_credit_card_item"
	FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
