/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-дек-2024 17:03:22 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

--DROP TABLE IF EXISTS item_transfer_funds CASCADE;

/* Create Tables */

CREATE TABLE item_transfer_funds
(
	id bigserial NOT NULL,
	item_id bigint NOT NULL,
	transfer_type varchar(50) NOT NULL,
	transfer_amount numeric(19,2) NOT NULL,
	commission numeric(19,2) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE item_transfer_funds ADD CONSTRAINT "PK_item_transfer_funds"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_item_transfer_funds_item" ON item_transfer_funds (item_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE item_transfer_funds ADD CONSTRAINT "FK_item_transfer_funds_item"
	FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
