/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 26-дек-2024 15:53:46 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

--DROP TABLE IF EXISTS item_mortgage CASCADE;

/* Create Tables */

CREATE TABLE item_mortgage
(
	id bigserial NOT NULL,
	item_id bigint NOT NULL,
	loan_amount numeric(19,2) NOT NULL,
	loan_term integer NOT NULL,
	interest_rate numeric(5,2) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE item_mortgage ADD CONSTRAINT "PK_item_mortgage"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_item_mortgage_item" ON item_mortgage (item_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE item_mortgage ADD CONSTRAINT "FK_item_mortgage_item"
	FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
