/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 23-дек-2024 17:19:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

--DROP TABLE IF EXISTS service CASCADE;

/* Create Tables */

CREATE TABLE service
(
	id bigint NOT NULL,
	code varchar(64) NOT NULL,
	name varchar(256) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE service ADD CONSTRAINT "PK_service"
	PRIMARY KEY (id)
;
