/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-дек-2024 17:44:01 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

/* Drop Tables */

--DROP TABLE IF EXISTS "order" CASCADE;

/* Create Tables */

CREATE TABLE "order"
(
	id bigserial NOT NULL,
	user_email varchar(256) NOT NULL,
	created_at timestamp without time zone NOT NULL,
	service_id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "order" ADD CONSTRAINT "PK_order"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_order_service" ON "order" (service_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "order" ADD CONSTRAINT "FK_order_service"
	FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 
