/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 24-дек-2024 18:27:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS item CASCADE
;

/* Create Tables */

CREATE TABLE item
(
	id bigint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE item ADD CONSTRAINT "PK_item"
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_item_order" ON item (id ASC)
;

CREATE INDEX "IXFK_item_service" ON item (id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE item ADD CONSTRAINT "FK_item_order"
	FOREIGN KEY (id) REFERENCES "order" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE item ADD CONSTRAINT "FK_item_service"
	FOREIGN KEY (id) REFERENCES service (id) ON DELETE No Action ON UPDATE No Action
;
